const state={session:null,selectedCase:"balanced_action",examples:[],resolvedIssues:[]};
const API_BASE=location.pathname.startsWith("/demos/stock")?"/api/stock":"";
const apiPath=path=>`${API_BASE}${path}`;
const $=selector=>document.querySelector(selector);
const money=value=>`€${Number(value).toFixed(2)}`;
const dateLabel=value=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${value}T00:00:00Z`));

const copy={
  balanced_action:{tag:"Buy and reduce",title:"What needs changing this week?",detail:"One product is running out. Another incoming line adds short-dated stock."},
  unsafe_shelf_life:{tag:"Protect shelf life",title:"Can we safely cancel this order?",detail:"Old stock exists, but it may not be suitable for a booked customer."},
  healthy_control:{tag:"Know when to stop",title:"Is the current plan already right?",detail:"The stock and incoming order may already cover the next four weeks."},
};

async function api(path,options={}){const response=await fetch(apiPath(path),{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const body=(response.headers.get("content-type")||"").includes("application/json")?await response.json():await response.text();if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function notice(message=""){const box=$("#notice");box.hidden=!message;box.textContent=message}

function scenarioButton(example){const item=copy[example.case_id];const button=document.createElement("button");button.type="button";button.className="scenario-option";button.dataset.caseId=example.case_id;button.setAttribute("role","radio");const tag=document.createElement("span");tag.textContent=item.tag;const title=document.createElement("strong");title.textContent=item.title;const detail=document.createElement("small");detail.textContent=item.detail;button.append(tag,title,detail);button.addEventListener("click",()=>selectScenario(example.case_id));return button}
function selectScenario(caseId){state.selectedCase=caseId;document.querySelectorAll(".scenario-option").forEach(button=>{const selected=button.dataset.caseId===caseId;button.classList.toggle("selected",selected);button.setAttribute("aria-checked",String(selected))})}

function currentAndSelected(decision){const current=Object.fromEntries(decision.current.views.map(row=>[row.view_id,row]));const selected=Object.fromEntries(decision.selected.views.map(row=>[row.view_id,row]));return{current,selected}}
function actionText(action,caseId){const cases=`${action.selected_cases} case${action.selected_cases===1?"":"s"}`;const meanings={
  order_now:["Order now",`Add ${cases}. It is needed before the next supplier delivery opportunity.`],
  cancel:["Do not buy",`Cancel the current ${action.current_cases}-case line before its change cut-off.`],
  buy_less:["Buy less",`Reduce from ${action.current_cases} to ${cases}.`],
  keep_order:["Keep the order",caseId==="unsafe_shelf_life"?"The older lot cannot meet the booked customer's shelf-life requirement.":"The full line is needed in the higher and irregular demand views."],
  buy_more:["Buy more",`Increase the line to ${cases}.`],no_order:["No order",`No purchase is needed for this product.`],
  };return meanings[action.action]}

function renderActions(decision,caseId){const container=$("#action-list");container.replaceChildren();decision.actions.filter(action=>action.action!=="no_order").forEach(action=>{const [label,detail]=actionText(action,caseId);const row=document.createElement("div");row.className="action-row";const tag=document.createElement("span");tag.className="action-tag";tag.textContent=label;const body=document.createElement("div");const name=document.createElement("strong");name.textContent=action.product_name;const reason=document.createElement("p");reason.textContent=detail;body.append(name,reason);const change=document.createElement("span");change.className="case-change";change.textContent=action.current_cases===action.selected_cases?`${action.selected_cases} cases`:`${action.current_cases} → ${action.selected_cases} cases`;row.append(tag,body,change);container.append(row)})}

function metric(title,before,after,formatter){const figure=document.createElement("figure");figure.className="metric";const caption=document.createElement("figcaption");caption.textContent=title;figure.append(caption);const maximum=Math.max(1,before,after);[["Before",before,"before"],["After",after,"after"]].forEach(([label,value,kind])=>{const row=document.createElement("div");row.className=`metric-row ${kind}`;const name=document.createElement("span");name.textContent=label;const amount=document.createElement("strong");amount.textContent=formatter(value);const rail=document.createElement("div");rail.className="rail";rail.setAttribute("aria-hidden","true");const bar=document.createElement("div");bar.className="bar";bar.style.width=`${100*value/maximum}%`;rail.append(bar);row.append(name,amount,rail);figure.append(row)});return figure}
function renderCharts(decision){const {current,selected}=currentAndSelected(decision);const before=current.higher,after=selected.higher;$("#charts").replaceChildren(
  metric("Cash for this week's plan",Number(decision.current.cash_eur),Number(decision.selected.cash_eur),money),
  metric("Projected expiry",before.expired_units,after.expired_units,value=>`${value} units`),
  metric("Booked units on time",before.booked_on_time_units,after.booked_on_time_units,value=>`${value} / ${after.booked_units}`),
)}

function renderDecision(session){const decision=session.decision;const {current,selected}=currentAndSelected(decision);const changed=decision.verdict==="change_plan";$("#decision").hidden=false;const titles={balanced_action:"Order Soup Cups. Cancel Oat Crackers.",unsafe_shelf_life:"Keep the Fruit Bars order.",healthy_control:"No changes are needed this week."};$("#decision-title").textContent=titles[session.case_id];$("#verdict").textContent=changed?"Change plan":"Keep plan";
  if(session.case_id==="balanced_action")$("#decision-copy").textContent="Soup Cups run short on 13 October without a new order. The Oat Crackers receipt is unnecessary and adds short-dated stock.";
  else if(session.case_id==="unsafe_shelf_life")$("#decision-copy").textContent="The warehouse has older Fruit Bars, but they arrive with too little shelf life for the booked hotel order. Keep all four incoming cases.";
  else $("#decision-copy").textContent="The current Tomato Jars order is needed under the higher and irregular demand views. Nothing is projected to expire in the next 28 days.";
  const firstRunOut=current.higher.run_outs[0];$("#run-out").textContent=firstRunOut?dateLabel(firstRunOut.date):"No shortage";$("#run-out-note").textContent=firstRunOut?`${firstRunOut.missing_units} units short · current plan`:"Selected plan · higher view";$("#expiry").textContent=`${selected.higher.expired_units} units`;$("#booked").textContent=`${selected.higher.booked_on_time_units} / ${selected.higher.booked_units}`;
  renderActions(decision,session.case_id);renderCharts(decision);
  $("#safety-copy").textContent=`${selected.higher.booked_on_time_units} of ${selected.higher.booked_units} booked units arrive on time in the selected plan. The same action was also checked against lower, nominal and irregular demand.`;
  if(decision.at_risk_lots.length){const units=decision.at_risk_lots.reduce((sum,row)=>sum+row.quantity_units,0);$("#risk-title").textContent=`${units} units still require attention`;$("#risk-copy").textContent="These units are shown in the expiry list with their lot and projected date. The buyer decides the commercial action; the tool does not invent a markdown or recovered revenue."}else{$("#risk-title").textContent="No lot needs action";$("#risk-copy").textContent="No projected expiry remains in the higher-demand view during this 28-day review."}
  const exportQuery=new URLSearchParams({case_id:session.case_id,issues:state.resolvedIssues.join(",")});$("#order-export").href=apiPath(`/api/sessions/${session.session_id}/export-order?${exportQuery}`);$("#risk-export").href=apiPath(`/api/sessions/${session.session_id}/export-risk?${exportQuery}`);$("#search-proof").textContent=`${decision.search_report.physically_replayed} valid plans were physically replayed. ${decision.search_report.survivors} protected every required outcome. The search was capped at ${decision.search_report.maximum_candidates}.`;$("#decision-hash").textContent=`Decision fingerprint: ${decision.decision_hash}`;
}

function render(session){state.session=session;notice();$("#review").hidden=false;$("#case-label").textContent=copy[session.case_id].title;$("#row-count").textContent=session.source_row_count;$("#input-hash").textContent=session.input_hash;const blockers=session.issues.filter(issue=>issue.blocks_planning);const actions=$("#issue-actions");actions.replaceChildren();if(blockers.length){$("#records-title").textContent="One answer is needed first.";$("#record-status").textContent="Waiting for you";$("#record-status").className="status";$("#record-copy").textContent="A missing unit changes how much stock is available. Confirm it before the plan is calculated.";blockers.forEach(issue=>{const row=document.createElement("div");row.className="issue-row";const body=document.createElement("div");const title=document.createElement("h3");title.textContent=issue.title;const detail=document.createElement("p");detail.textContent=issue.detail;body.append(title,detail);const button=document.createElement("button");button.type="button";button.className="button primary";button.textContent=issue.action_label;button.addEventListener("click",()=>resolveIssue(issue.issue_id,button));row.append(body,button);actions.append(row)});$("#decision").hidden=true}else{$("#records-title").textContent="The stock position is ready.";$("#record-status").textContent="Checked";$("#record-status").className="status success";$("#record-copy").textContent="Lots, expiry dates, booked orders, incoming purchases and supplier terms now agree. No decision-critical fact was silently guessed.";renderDecision(session)}}

async function loadCase(){const button=$("#review-button");button.disabled=true;button.textContent="Checking stock…";state.resolvedIssues=[];try{render(await api("/api/sessions/example",{method:"POST",body:JSON.stringify({case_id:state.selectedCase})}));$("#review").scrollIntoView({behavior:"smooth",block:"start"})}catch(error){notice(error.message)}finally{button.disabled=false;button.textContent="Review this week's stock"}}
async function resolveIssue(issueId,button){button.disabled=true;button.textContent="Checking…";try{const resolvedIssues=[...new Set([...state.resolvedIssues,issueId])];state.resolvedIssues=resolvedIssues;render(await api(`/api/sessions/${state.session.session_id}/resolve`,{method:"POST",body:JSON.stringify({case_id:state.selectedCase,issue_id:issueId,resolved_issue_ids:resolvedIssues})}));$("#decision").scrollIntoView({behavior:"smooth",block:"start"})}catch(error){notice(error.message);button.disabled=false}}
async function reset(){if(!API_BASE&&state.session?.session_id){try{await api(`/api/sessions/${state.session.session_id}`,{method:"DELETE"})}catch(error){notice(error.message);return}}state.session=null;state.resolvedIssues=[];$("#review").hidden=true;notice();$("#scroll-region").scrollTo({top:0,behavior:"smooth"})}
async function init(){try{const returnLink=$(".studio-back");const requestedReturn=new URLSearchParams(location.search).get("return");if(requestedReturn){const target=new URL(requestedReturn,location.origin);if(["http:","https:"].includes(target.protocol))returnLink.href=target.href}else if(location.pathname.startsWith("/demos/")){returnLink.href="/work/"}else{returnLink.href="http://127.0.0.1:4321/work/"}state.examples=await api("/api/examples");$("#scenario-list").replaceChildren(...state.examples.map(scenarioButton));selectScenario(state.selectedCase);$("#review-button").addEventListener("click",loadCase);$("#reset").addEventListener("click",reset)}catch(error){notice(error.message)}}
document.addEventListener("DOMContentLoaded",init);
